server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://docker.for.mac.host.internal:3306/newdb
    username: root
    password: Gaurav@128 # Consider using an environment variable for sensitive data
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Use 'update' for development
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: puniagaurav14@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        security: DEBUG