server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newdb
    username: root
    password: root # You might want to use an environment variable for sensitive data
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Change to 'update' or 'validate' for production
      dialect: org.hibernate.dialect.MySQL8Dialect # Explicit dialect for MySQL 8
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: puniagaurav14@gmail.com
    password: tgcdsqqwaqibnwrj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        security=DEBUG: